apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-modules
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: slidge-matrix-secret
  namespace: default
type: Opaque
stringData:
  SECRET: xxxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: slidge-whatsapp-secret
  namespace: default
type: Opaque
stringData:
  SECRET: xxxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: slidge-discord-secret
  namespace: default
type: Opaque
stringData:
  SECRET: xxxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slidge-matrix-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slidge-whatsapp-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slidge-discord-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prosody
  name: prosodyv6
  namespace: default
  annotations:
    metallb.io/address-pool: v6home
    metallb.io/loadBalancerIPs: fd00:db80:1::xx/128
spec:
  type: LoadBalancer
  ports:
  - name: s2s
    port: 5269
    targetPort: s2s
  - name: c2s
    port: 5222
    targetPort: c2s
  - name: http
    port: 5280
    targetPort: http
  - name: https
    port: 5281
    targetPort: https
  selector:
    app: prosody
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prosody
  name: prosody
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.x.y
spec:
  type: LoadBalancer
  ports:
  - name: s2s
    port: 5269
    targetPort: s2s
  - name: c2s
    port: 5222
    targetPort: c2s
  - name: http
    port: 5280
    targetPort: http
  - name: https
    port: 5281
    targetPort: https
  selector:
    app: prosody
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1000M
    nginx.ingress.kubernetes.io/proxy-body-size: 1000M
  generation: 1
  name: prosody
  namespace: default
spec:
  ingressClassName: nginx-lan
  rules:
  - host: xmpp.example.com
    http:
      paths:
      - backend:
          service:
            name: prosody
            port:
              number: 5280
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - xmpp.example.com
    - muc.example.com
    - example.com
    secretName: prosody-cert

