apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-modules
  name: prosody-modules
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 100Mi
---
{{- if .Values.slidge }}
{{- if .Values.slidge.matrix }}
{{- if .Values.slidge.matrix.enabled }}
{{- if eq(.Values.slidge.matrix.enabled) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-matrix-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
---
{{- if .Values.slidge }}
{{- if .Values.slidge.signal }}
{{- if .Values.slidge.signal.enabled }}
{{- if eq(.Values.slidge.signal.enabled) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-signal-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
---
{{- if .Values.slidge }}
{{- if .Values.slidge.whatsapp }}
{{- if .Values.slidge.whatsapp.enabled }}
{{- if eq(.Values.slidge.whatsapp.enabled) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-whatsapp-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
---
{{- if .Values.slidge }}
{{- if .Values.slidge.discord }}
{{- if .Values.slidge.discord.enabled }}
{{- if eq(.Values.slidge.discord.enabled) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-discord-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prosody-helm.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.storageClass }}
  resources:
    requests:
      storage: 11Gi
