apiVersion: v1
kind: Service
metadata:
  name: {{ include "prosody-helm.fullname" . }}
  labels:
    {{- include "prosody-helm.labels" . | nindent 4 }}
  annotations:
    {{- .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ .Values.service.ports }}
  selector:
    {{- include "prosody-helm.selectorLabels" . | nindent 4 }}

